[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
syn = { version = "2.0.100", features = ["full"] }
quote = "1.0.40"
darling = "0.20.10"
regex = "1.11.1"
